### ISSUE TITLE
Error when using speech

### ISSUE THREAD

**Issue by DarkmatterVale** [GCI-2015-GPW/DevAssist#2]
When running the terminal example, after you speak once, the program crashes with the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/speech_recognition/__init__.py", line 414, in threaded_listen
    if running[0]: callback(self, audio)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/speech_recognition/__init__.py", line 95, in __exit__
    if not self.stream.is_stopped():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyaudio.py", line 543, in is_stopped
    return pa.is_stream_stopped(self._stream)
IOError: [Errno -9988] Stream closed
```

I am running PyAudio 0.2.9 and OS X 10.10.5. Any ideas why this is happening?

**Comment by vincentes** [comment]
You should create an issue [here](https://github.com/jleb/pyaudio).
